### ISSUE TITLE
JWT uses base64url encoding, not base64 encoding

### ISSUE THREAD

**Issue by finlay** [simonh1000/elm-jwt#1]
base64 and base64url encoding are different in the last two characters used, 
ie, base64 -> '+/', or base64url ->  '-_'
see https://en.wikipedia.org/wiki/Base64#URL_applications

To make the decode  Jwt.decodeToken function work I needed to add this simple function to pre-process the token: 
``` elm
unurl = 
    let fix c = 
          case c of 
            '-' -> '+'
            '_' -> '/'
            c   -> c
    in String.map fix
```

Then it works great.

This fix could be added to the elm-jwt library, or the base64 library expanded to include a urldecode version.

**Comment by simonh1000** [comment]
Thanks. I'm happy to take a PR, but will otherwise ad it directly

**Comment by simonh1000** [comment]
Have pushed a new release with your function and some length handling per my answer

**Comment by finlay** [comment]
Great! 

That was quick... 

Finlay

**Comment by simonh1000** [comment]
You're welcome - and you provided half the code!
Hope you will consider starring the library if you find it useful.

**Comment by finlay** [comment]
Starred...
