### ISSUE TITLE
204 response from API

### ISSUE THREAD

**Issue by joshhornby** [simonh1000/elm-jwt#11]
Hi,

Thanks for this package 👍 

My API gives a 204 response with no content, but this throw an `HttpError`: 

```
HttpError (BadPayload "Given an invalid JSON: Unexpected end of JSON input" { status = { code = 204, message = "No Content" }, headers = Dict.fromList [("Content-Type","text/html; charset=UTF-8")], url = "http://madeupurl.com", body = "" })
```

Do you have any suggestions for how to handle this? I have tried this but still get the same error:

```
emptyDecoder : Json.Decoder String
emptyDecoder =
    Json.value |> Json.andThen (\_ -> Json.succeed "true")
```

**Comment by simonh1000** [comment]
have you tried 
```
emptyDecoder : Json.Decoder String
emptyDecoder =
    Json.succeed "true"
```

If that does not work, then you have to build your request object yourself. For example 

```
let 
  req = createRequest method token url body (Json.succeed "")
  req_ = { req | expect = Http.expectString }
...

```

**Comment by joshhornby** [comment]
Thanks for the response @simonh1000 

`Json.succeed "true"` doesn't work, can you prove the full example for building a request object? What needs to be in the `in` part of the `let` block?

**Comment by simonh1000** [comment]
See https://github.com/simonh1000/elm-jwt/blob/master/src/Jwt.elm#L190 and use expectText instead

**Comment by MazeChaZer** [comment]
I'm having the same issue for `DELETE` requests where the response obviously has no body.

**Comment by simonh1000** [comment]
Ok, I will split up the functions a little more

**Comment by simonh1000** [comment]
See https://github.com/simonh1000/elm-jwt/blob/master/examples/phoenix/web/elm/App.elm#L323 for example of how I would now tackle this issue

**Comment by MazeChaZer** [comment]
I'm not 100% percent sure, but I think useing `(Json.succeed "")` will not work. Before the decoder is even applied to the response, `JSON.parse()` is called because the `expectJson` part is still hardcoded in the request creation method. But the JSON parsing will fail for an empty response. I think the solution would be not to assume that the response contains any kind of JSON and remove the `expectJson` from the function.

**Comment by simonh1000** [comment]
I'm going to remove the expectJson as this is a library for accessing an authenticated REST API. But the change I published yesterday makes it quite possible to change the expect to something else.
