### ISSUE TITLE
Examples included under elm-stuff/

### ISSUE THREAD

**Issue by stoft** [simonh1000/elm-jwt#14]
I just set up a phoenix project to try out jwt and I get the following error:
'== Compilation error on file lib/tinker_web/web/elm/elm-stuff/packages/simonh1000/elm-jwt/5.0.0/examples/phoenix/web/gettext.ex ==
warning: no configuration found for otp_app :jwt_example and module JwtExample.Endpoint
** (ArgumentError) unknown application: :jwt_example'

All though this was a good thing for me since I hadn't yet discovered the examples, they probably shouldn't be included in elm-stuff/ when building. (Had I placed my Elm code outside Phoenix it would be different of course.)

**Comment by simonh1000** [comment]
Hmm, it's very common to include examples in a repo that is being shared. I think your problem is that you have set up gulp/webpack/... to look too widely for *.elm files.

**Comment by stoft** [comment]
I agree, examples are good! In this case it's mix/Elixir throwing the error, probably due to a different version of Elixir and / or Phoenix. Simply deleting the examples from the build solves the issue but in a CI situation it may not. I'm unsure what a good solution would be, I really like the example and that it includes Phoenix because that's what I'm targeting. Perhaps lift out the Phoenix part (since it's an Elm-lib) into a separate repo and reference it from this one in the readme?

**Comment by zwilias** [comment]
Something I've seen some other folks do (for example in elm-community/webgl) is to remove all the non-elm-stuff before tagging a release; so the released libraries are minimal but the repo contains extra stuff.

They even have a [little script](https://github.com/elm-community/webgl/blob/master/release.sh) for it :)

**Comment by simonh1000** [comment]
That's fantastic - i've made a copy of the script, and used it to release a minor update that does not include the examples, so i can close this
