### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by kingsleyh** [simonh1000/elm-jwt#16]
Hi

I cloned this repo and ran the npm install and gulp - but the elm does not compile:

```
-- NAMING ERROR -------------------------------------------------- ./src/App.elm

Cannot find variable `Jwt.checkTokenExpirey`.

138|             , Jwt.checkTokenExpirey token
                   ^^^^^^^^^^^^^^^^^^^^^
`Jwt` does not expose `checkTokenExpirey`. Maybe you want one of the following?

    Jwt.checkTokenExpiry

-- NAMING ERROR -------------------------------------------------- ./src/App.elm

This usage of variable `tokenDecoder` is ambiguous.

237|                         decodeToken tokenDecoder tokenString
                                         ^^^^^^^^^^^^
Maybe you want one of the following?

    Decoders.tokenDecoder
    Jwt.tokenDecoder
```

the first looks like a spelling mistake where checkTokenExpiry is spelled incorrectly - and the second one I'm not sure whether it should be decoding from Jwt or Decoders?

**Comment by kingsleyh** [comment]
In App.elm I had to fix the spelling on line 138 - to Jwt.checkTokenExpiry and then I had to modify line 237 to Decoders.tokenDecoder in order to get the elm to compile.

**Comment by simonh1000** [comment]
Thanks - I should upgrade the whole build environment for the Node example, but have at least fixed everything per your very helpful contribution :-)

**Comment by simonh1000** [comment]
Master now has a full update of nodejs example
