### ISSUE TITLE
Support elm/http 2.0.0

### ISSUE THREAD

**Issue by Munksgaard** [simonh1000/elm-jwt#20]

**Comment by Munksgaard** [comment]
In the meantime, @JonRowe has created a fork that just rips out the old request functions: https://github.com/JonRowe/elm-jwt/commit/54a65b33b362cb8daa2fcc4dd574aeec2d3c02b6.

**Comment by JonRowe** [comment]
I feel a better approach would be to have two libraries, one that does the core token functions (which is all and many others need) and one which adds `http` functions :)

**Comment by simonh1000** [comment]
Sorry, been busy on other things. I need to look into http 2 it seems. Will get back to you

**Comment by simonh1000** [comment]
Have started reworking the code on branch http2 - as it's going to be a major release, would welcome feedback on the API.

@JonRowe with --optimize and 0.19 I feel under less pressure now to make libraries ever more atomic, but making a clearer separation of uses could make sense

**Comment by simonh1000** [comment]
Fixed in 7.0.0
