### ISSUE TITLE
variant of expiry check helpers that exposes remaining time?

### ISSUE THREAD

**Issue by robx** [simonh1000/elm-jwt#23]
I'd like to check not just whether a token is expired, but whether it's close to expiry. To that extent, an API like the following would be great (which would easily allow implementing the current specialized functions):

```
getTokenExpirationMillis : String -> Result JwtError Int
getTokenExpirationMillis = ...

getTokenTimeToExpirationMillis : String -> Task JwtError Int
getTokenTimeToExpirationMillis = ...
```

What do you think? I'd be happy to provide a PR if you think this is a good idea.

**Comment by simonh1000** [comment]
I'd welcome a PR for `getTokenExpirationMillis` but I think the latter should be left to users
