### ISSUE TITLE
Feature request: minimal json-server example

### ISSUE THREAD

**Issue by pdamoc** [simonh1000/elm-jwt#6]
Please create a minimal `json-server` auth example.

**Comment by simonh1000** [comment]
Hi Pete,  what exactly did you have in mind. A server is a pretty complex beast, but the only real breaks with the initial bootstrapping code in both the phoenix and node examples is the jwt code, and that's the emphasis of the accompanying blog http://simonh1000.github.io/2016/05/phoenix-elm-json-web-tokens/. On the elm side, I am pretty minimal already.

**Comment by pdamoc** [comment]
I was thinking that a `json-server` example could be taken and expanded by a person wanting to play with `elm-jwt`. It would be like a lighter version of the node and phoenix examples.

**Comment by pdamoc** [comment]
After playing myself with the idea I realized that it would not be considerably simpler than the node example once one takes into consideration session management so... this would be redundant.
