### ISSUE TITLE
How are we supposed to include csrf headers?

### ISSUE THREAD

**Issue by IvanCaceres** [simonh1000/elm-jwt#7]
Would it be a good idea to add an extra argument to the authenticate method, or maybe set some kind of default to include or add the csrf header to the elm http send request.

Right now it looks like i have to modify the JWT library itself to add in my csrf token header.

**Comment by simonh1000** [comment]
Hi, I can see that csrf are related to jwt, but they do serve a different purpose. There are a lot of different things that could be added to http headers, including csrf tokens, and I fear that creating bespoke functions is not a good option. 

In your case, I would suggest going back to the Http library primitives and using `send` with some inspiration from my variant https://github.com/simonh1000/elm-jwt/blob/master/Jwt.elm#L115

**Comment by IvanCaceres** [comment]
Thank you for the quick response, i think this solves my question so i'll close this.
