### ISSUE TITLE
Using package with Elm inside a Phoenix app

### ISSUE THREAD

**Issue by plamb** [simonh1000/elm-jwt#8]
This is not really an error but more of an FYI.

The alternative to having Elm as it's own separate app is to add Elm into the Phoenix project itself (./web/elm is the currently favored directory) and add brunch-elm or use webpack instead of brunch. This causes a problem because mix wants to compile the example program from this package (which generates some errors). By default mix is going to include anything in the web directory and try and compile it. 

For those coming to this via a google search. The better way to handle this is to use ./elm instead of ./web/elm inside your phoenix app. Which does require some changes to brunch or web pack config besides just moving the directory.

**Comment by simonh1000** [comment]
Thanks, I know, and I should get round to updating the example to latest versions etc. at some stage. Will leave this open as a reminder!

**Comment by simonh1000** [comment]
I have now rewritten the example.
